Follow standard explainer template
webmachinelearning/model-loader pull request #14
Opened 2021-11-12 16:34 UTC by jbingham

To make the explainer more readable, this update follows a standard format.

2021-11-12 17:26 UTC, anssiko requested changes
Thanks for moving this to the standard format!

2021-11-12 17:26 UTC, anssiko commented on explainer.md
> +*   [Web ML Working group](https://www.w3.org/groups/wg/webmachinelearning)
This spec is currently in the Community Group.

```suggestion
*   [Web Machine Learning Community Group](https://www.w3.org/groups/cg/webmachinelearning)

```

2021-11-12 17:26 UTC, anssiko commented on explainer.md
> +Like the related [Web NN](https://webmachinelearning.github.io/webnn) proposal, some of the main the goals are:
Given WebNN is a WG deliverable, it is preferred to use a term "specification" over "proposal".

```suggestion
Like the related [Web Neural Network API](https://webmachinelearning.github.io/webnn) specification, some of the main the goals are: 
```

2021-11-12 17:26 UTC, anssiko commented on explainer.md
> +These and other  APIs are already widely used by many products and organizations for large volumes of requests.
Whitespace nit.

```suggestion
These and other APIs are already widely used by many products and organizations for large volumes of requests.

```

2021-11-12 17:26 UTC, anssiko commented on explainer.md
> +Developers want to run custom models too. Application-specific APIs can cover the top use cases only, and with limited flexibility
Nit, trailing "."
```suggestion
Developers want to run custom models too. Application-specific APIs can cover the top use cases only, and with limited flexibility.
```

2021-11-12 17:26 UTC, anssiko commented on explainer.md
> +[proposed charter]https://www.w3.org/2021/02/proposed-machine-learning-charter.html() for the Web ML Working Group.
```suggestion
The Model Loader API is currently included as a Tentative Specification in the
[Web Machine Learning Working Group Charter](https://www.w3.org/2021/04/web-machine-learning-charter.html).
```

2021-11-12 17:26 UTC, anssiko commented on explainer.md
> +*  Salesforce: Collaborating in Working Group
Whitespace nit:
```suggestion
*   Salesforce: Collaborating in Working Group
```

2021-11-16 15:45 UTC, jbingham commented
I think I accepted all of your changes, @anssiko. It's showing up as Outdated, rather than accepted though. Sorry about that! Can you confirm?

2021-11-16 17:17 UTC, anssiko approved these changes

2021-11-16 17:17 UTC, anssiko commented
Yes, all good. 👍

2021-11-16 17:24 UTC, merged

2021-11-17 01:09 UTC, huningxin reviewed
LGTM